service: hello
provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-northeast-1'} 
  timeout: 30
  memorySize: 512
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "secretsmanager:GetSecretValue"
      Resource:
        - "*"
plugins:
  - serverless-python-requirements
functions:
  hello:
    handler: handler.request
    environment: 
      SLACK_API_SIGNING_SECRET: slack/secret
    events:
      - http:
          path: '/'
          method: post
custom:
  pythonRequirements:
    usePipenv: true